// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwDJYLpzuBeIDca2CyWe3xgPMtVpTs67k',
    appId: '1:1005189399100:web:b1c7aa8c59c3770affb939',
    messagingSenderId: '1005189399100',
    projectId: 'flutterauth-44ee2',
    authDomain: 'flutterauth-44ee2.firebaseapp.com',
    storageBucket: 'flutterauth-44ee2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwJGjVxrco7cpdikI6frC46RnYQtKcrSU',
    appId: '1:1005189399100:android:92f966d6ccbbcd62ffb939',
    messagingSenderId: '1005189399100',
    projectId: 'flutterauth-44ee2',
    storageBucket: 'flutterauth-44ee2.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoBFD30xCBp18s7pLCBGcm3Bpr7bpuuqs',
    appId: '1:1005189399100:ios:8178389e4bd23904ffb939',
    messagingSenderId: '1005189399100',
    projectId: 'flutterauth-44ee2',
    storageBucket: 'flutterauth-44ee2.firebasestorage.app',
    iosBundleId: 'com.example.brainvault',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoBFD30xCBp18s7pLCBGcm3Bpr7bpuuqs',
    appId: '1:1005189399100:ios:8178389e4bd23904ffb939',
    messagingSenderId: '1005189399100',
    projectId: 'flutterauth-44ee2',
    storageBucket: 'flutterauth-44ee2.firebasestorage.app',
    iosBundleId: 'com.example.brainvault',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwDJYLpzuBeIDca2CyWe3xgPMtVpTs67k',
    appId: '1:1005189399100:web:b194fa18eb8aab4cffb939',
    messagingSenderId: '1005189399100',
    projectId: 'flutterauth-44ee2',
    authDomain: 'flutterauth-44ee2.firebaseapp.com',
    storageBucket: 'flutterauth-44ee2.firebasestorage.app',
  );
}
